project_id = "kbxdwrvxrnfkqvpselwz"

[functions.send-reservation-email]
verify_jwt = false

[functions.send-laiga-reservation]
verify_jwt = false

[functions.track-visitor-location]
verify_jwt = false