-- Atualizar as últimas descrições dos pesquisadores

UPDATE researchers 
SET description = 'Possui doutorado em Geofísica pela Universidade Federal da Bahia (2006) e mestrado em Geofísica pela Universidade Federal da Bahia (1999). É graduada em Engenharia Sanitária e em Engenharia Civil, possui experiência profissional na área ambiental e em projetos de Sistemas de Abastecimento de Água. Atualmente é professora Associada IV e pesquisadora no Instituto de Geociências da UFBA, atuando principalmente nos seguintes temas: Geofísica de Exploração de Águas Subterrâneas e Geofísica Aplicada a Estudos Ambientais, Métodos Geofísicos Elétricos e Gestão de Resíduos Sólidos e de Recursos Hídricos.'
WHERE name = 'Susana Silva Cavalcanti';

UPDATE researchers 
SET description = 'Licenciada em Matemática pela Universidade Federal do Pará (2005), Mestra em Geofísica na área de concentração de Gravimetria e Magnetometria pela Universidade Federal do Pará (2007). Bacharel em Enfermagem pela Universidade do Estado do Pará (2008). Foi professora de Biofísica no curso de graduação em Enfermagem na Universidade da Amazônia (2009). Exerceu a função de coordenadora de atividades na disciplina de Geofísica no Projeto "Univesp - Licenciatura em Ciências", polo de São Carlos (2013). Doutora em Geofísica pela Universidade do Estado de São Paulo (2014) na área de Métodos Elétricos, com ênfase na Inversão de dados de Potencial Espontâneo e Modelagem de fluxo de água no meio poroso. Atuou como pesquisadora visitante no Lenep- Laboratório de engenharia e exploração de petróleo, bolsista do PRH-PB 226, no laboratório de petrofísica (2014). Admitida como professora 40h DE no Departamento de Geofísica do IGEO/UFBA (2015) onde atualmente é professora adjunta, nível 4. Atua como pesquisadora no Núcleo de Estudos Hidrogeológicos e do Meio Ambiente (NEHMA) em projetos de estudos de aterros sanitários e água subterrânea. Colaboradora nos projetos de extensão "Geoarretadas", "Seminário de água" e "MUGEO-Museu de Geociências". Cargos: Vice-chefe do DGf/UFBA de 31/05/2016 a 26/09/22. Chefe do DGf/UFBA desde 27/09/22. Conselheira da Regional Nordeste da SBGF- Sociedade Brasileira de Geofísica 2021-2025.'
WHERE name = 'Suzan Souza de Vasconcelos';

UPDATE researchers 
SET description = 'Possui Graduação em Matemática pela Universidade Federal do Rio de Janeiro (1983) e Doutorado em Geofísica pela UFBA, Universidade Federal da Bahia, (1994). Realizou Pesquisa a nível de Pós-Doutorado no Departamento Terra-Atmosfera-Oceano da Escola Normal Superior de Paris na França (1997-1999). Atualmente é Professor Associado da UFBA e Pesquisador do Centro de Pesquisa em Geofísica e Geologia da UFBA. Tem experiência na área de Geociências, com ênfase em Inversão Geofísica, atuando principalmente nos seguintes temas: Inversão Sísmica, Modelagem Sísmica, Traçamento de Raios Sísmicos, e Matemática Aplicada à Geofísica.'
WHERE name = 'Wilson Mouzer Figueiró';