-- Continuar atualizando descrições dos pesquisadores

UPDATE researchers 
SET description = 'Possui graduação em Oceanologia pela Universidade Federal do Rio Grande (2005), mestrado em Ecologia pela Universidade Federal do Rio Grande do Norte (2007) e doutorado em Oceanografia Física, Química e Geológica pela Universidade Federal do Rio Grande (2014). Professor Adjunto na UFBA. Atualmente coordenador do curso de Oceanografia da UFBA. Tem experiência na área de Oceanografia, com ênfase em Oceanografia Geológica, atuando principalmente nos seguintes temas: Sismoestratigrafia, Estratigrafia de Sequências, Morfodinâmica Costeira e Oceânica, Interação Oceano-Atmosfera, Geofísica Marinha, Ilhas Oceânicas e Mergulho Científico.'
WHERE name = 'Arthur Antonio Machado' OR name = 'Arthur Antônio Machado';

UPDATE researchers 
SET description = 'Sou oceanógrafa, Professora Adjunta do Departamento de Oceanografia na Universidade Federal da Bahia. Tenho grau de Doutorado e Mestrado em Oceanografia pela Universidade Federal de Pernambuco. Atuo na área de monitoramento, mapeamento e conservação, sensoriamento remoto e geoprocessamento aplicado ao ambiente marinho e costeiro, principalmente em recifes de coral, e na obtenção e tratamento de dados de campo. Possui experiência em expedições Reef Check Brasil na APA Costa dos Corais (PE/AL), PARNAMAR Fernando de Noronha, PARNAMAR Abrolhos, entre outras.'
WHERE name = 'Camila Brasil Louro da Silveira';

UPDATE researchers 
SET description = 'Possui graduação em Geologia pela Universidade de Brasília (1978), mestrado em Exploração Mineral pela Universidade de Londres- Royal School of Mines (1985) e doutorado em Geologia pela Universidade Federal da Bahia (2002). Trabalhou como geólogo de campo e petrógrafo na Companhia Baiana de Pesquisa Mineral no período de 1978-1997, quando desenvolveu trabalhos de mapeamento geológico em escalas regional e de detalhe na prospecção de ouro, vanádio, sulfetos de metais-base e rocha fosfática em unidades de rochas pré-cambrianas. No período entre 2002 e 2020, trabalhou na Petrobras como geólogo no acompanhamento de poços e nas áreas de sedimentologia, estratigrafia e de tectônica rúptil na exploração e explotação de petróleo nas bacias rifte, mesozóicas, do Recôncavo e do Tucano Sul. Atualmente é Professor Associado III na Universidade Federal da Bahia, na cadeira de Geologia Estrutural, cargo que ocupa desde 2010. Os interesses de estudo e pesquisa nas áreas de Geociências incluem petrologia metamórfica e sua relação com a deformação regional durante a tectônica colisional de blocos continentais; tectônica de bacias e petrologia sedimentar com ênfase em diagênese estrutural associada a deformação rúptil em bacias rifte. Nestas áreas, orientou trabalhos de conclusão de curso em geologia, tem publicações em revistas de geociências, nacionais e internacionais com corpo editorial, bem como, revisou manuscritos para os seguintes periódicos: Marine and Petroleum Geology, Journal of South American Earth Sciences, Journal of Structural Geology e Journal of Metamorphic Petrology.'
WHERE name = 'Carlson de Matos Maia Leite';

UPDATE researchers 
SET description = 'Possui graduação em Geologia pela Universidade Federal da Bahia (2006), mestrado em Geologia pela Universidade Federal da Bahia (2009) e doutorado em Geologia pela Universidade Federal da Bahia (2014). Atualmente é professor adjunto da Universidade Federal da Bahia. Tem experiência na área de Geociências, com ênfase em Petrologia, Metalogênese e Exploração Mineral, atuando principalmente nos seguintes temas: petrogênese, geocronologia, geoquímica isotópica e geologia estrutural.'
WHERE name = 'Edson Emanuel Starteri Sampaio';

UPDATE researchers 
SET description = 'Possui graduação em Geologia pela Universidade Federal da Bahia (2003), mestrado em Geologia pela Universidade Federal da Bahia (2006) e doutorado em Geologia pela Universidade Federal da Bahia (2011). Atualmente é professor adjunto da Universidade Federal da Bahia. Tem experiência na área de Geociências, com ênfase em Recursos Hídricos e Ambientais, atuando principalmente nos seguintes temas: hidrogeologia, geofísica aplicada, geologia ambiental e gestão de recursos hídricos.'
WHERE name = 'Eduardo Reis Viana Rocha Junior';

UPDATE researchers 
SET description = 'Possui graduação em Geologia pela Universidade Federal da Bahia (1995), mestrado em Geologia pela Universidade Federal da Bahia (1998) e doutorado em Geologia pela Universidade Federal da Bahia (2002). Atualmente é professora associada da Universidade Federal da Bahia. Tem experiência na área de Geociências, com ênfase em Geologia, atuando principalmente nos seguintes temas: geoquímica, petrologia metamórfica, geocronologia e evolução crustal.'
WHERE name = 'Jailma Santos de Souza de Oliveira';

UPDATE researchers 
SET description = 'Possui graduação em Geologia pela Universidade Federal da Bahia (1977), mestrado em Geologia pela Universidade Federal da Bahia (1982) e doutorado em Geologia pela Universidade Federal da Bahia (1990). Atualmente é professor titular da Universidade Federal da Bahia. Tem experiência na área de Geociências, com ênfase em Geologia Estrutural e Tectônica, atuando principalmente nos seguintes temas: evolução crustal, metamorfismo, tectônica e geologia precambriana.'
WHERE name = 'Johildo Salomão Figuerêdo Barbosa';

UPDATE researchers 
SET description = 'Graduado em Geologia pela Universidade Federal da Bahia (1982), mestrado em Geoquímica e Meio Ambiente pela Universidade Federal da Bahia (1992), doutorado em Geociências pela Universidade Estadual de Campinas (2000) e pós-doutorado em evolução tectônica de Bacias Sedimentares pela UFBA (2008) e pesquisador visitante sênior em Modelagem Física de bacias tipo Riftes pelo ESD do Royal Holloway da Universidade de Londres (2022-2023). Publicou dezenas de artigos em revistas indexadas nacionais e internacionais, editou e escreveu livros temáticos e capítulos de livros. Coordena e vice-coordena diversos projetos de pesquisa financiados pelo CNPq e pela PETROBRAS. Orienta monografias de graduação, mestrado e doutorado. Foi Professor Associado III do Centro Federal de Educação Tecnológica da Bahia, atualmente é professor Associado III do Instituto de Geociências da Universidade Federal da Bahia, pesquisador permanente do Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq), é revisor de artigos para revistas nacionais e internacionais de corpo editorial. Participou de cursos de aperfeiçoamento no Brasil, Sul da África, Alpes, Reino Unido e Cráton da China. Tem experiência na área de Geociências, com ênfase em Geologia Estrutural, Tectônica e Mecânica de Rochas, atuando principalmente nos seguintes temas: Geologia da Bahia, do Brasil, da América do Sul, da África, da Europa e Asia, Geomorfologia Estrutural, Reologia de Magmas, Modelagem Física Analógica, Reconstituição de paleocontinentes, Mecânica de Rochas/Geotecnia, Dinâmica evolutiva de Bacias Sedimentares, Neotectônica, Dinâmica de zonas de cisalhamento e Prospecção de hidrocarbonetos e água subterrânea.'
WHERE name ILIKE '%Luiz César%' OR name ILIKE '%Luiz Cesar%';