// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdjmnrzqligktlxphfwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kam1ucnpxbGlna3RseHBoZndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTcyOTUsImV4cCI6MjA3MjY3MzI5NX0.AHcUHVx9X9sl0Tw5koIPIgHID7E0q7eJ0Tuu6oLG5-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});